### PR TITLE
added kill command, color updates, and manual IP input

### PR DESCRIPTION
**Pull request by 0d1nss0n**
added a kill (session number) command, pop of color added to main script, added option to manually enter an IP address when generating a payload

### CODE REVIEW

**Comment by 0d1nss0n** [comment]
just a few updates to colorize the main headhunter script, added a kill session command, and added the choice to enter an IP Address manually when generating a payload

**Review by Lionskey — APPROVED** [review]

**Review by Lionskey — COMMENTED** [review]
Hey man, thank you so much for the contributions! Just wanted to let you know that only PR's sent to the unstable branch will be accepted after this. 

I also wanted to discuss a little about the future of the project. I'm currently working on implementing the ssl socket wrapper library. This will allow us to hold an interactive shell which redirects the stdin, stdout, and stderr. 

The current psudo shell isn't very good in my opinion, so I'm focused on changing that.

Thank you again for the contributions, and happy hacking!

**Comment by 0d1nss0n** [comment]
@Lionskey 
Sick, got it. I've also been working on adding a function when generating a payload to obfuscate the code.

**Comment by 0d1nss0n** [comment]
But I agree lol the pseudo shell is a nice starting place but getting it upgraded to a full shell would be killer.

**Pull request merged**
